/**
 * Placeholder type definitions for Virtuoso templates
 */

export interface Placeholder {
  name: string;           // Name without braces
  fullMatch: string;      // e.g., "{{name}}"
  type: PlaceholderType;
  startIndex: number;
  endIndex: number;
}

export type PlaceholderType =
  | 'user'
  | 'id'
  | 'timestamp'
  | 'env';

export interface ParsedTemplate {
  original: string;
  placeholders: Placeholder[];
  hasAutoGeneratedFields: boolean;
}

export interface PlaceholderValues {
  [key: string]: string;
}

export interface ResolvedTemplate {
  xml: string;
  generatedIds: Record<string, string>;
}
