import {
  parsePlaceholders,
  resolvePlaceholders,
  validatePlaceholders,
} from '../placeholderParser';

describe('parsePlaceholders', () => {
  it('detects placeholder types and positions', () => {
    const template = '<iq id="{id}" to="{TO_JID}"><body>{message}</body>{timestamp}</iq>';
    const parsed = parsePlaceholders(template);

    expect(parsed.placeholders).toHaveLength(4);
    expect(parsed.hasAutoGeneratedFields).toBe(true);

    const types = parsed.placeholders.map((ph) => ph.type).sort();
    expect(types).toEqual(['env', 'id', 'timestamp', 'user']);
  });
});

describe('resolvePlaceholders', () => {
  it('keeps placeholders when no value is provided', () => {
    const template = '<iq id="{id}">{id}</iq>';
    const result = resolvePlaceholders(template, {}, { autoGenerate: true });

    expect(result.generatedIds['id']).toBeUndefined();
    expect(result.xml).toBe(template);
  });

  it('auto-generates an id when a user value is an alias token', () => {
    const template = '<iq id="{id}">{id}</iq>';
    const result = resolvePlaceholders(template, { id: '${id-test}' }, { autoGenerate: true });

    const generated = result.generatedIds['test'];
    const id = generated ?? '';
    expect(id).toBeDefined();
    expect(result.generatedIds['id']).toBe(id);
    expect(result.xml).toContain(id);
    expect(result.xml.match(new RegExp(id, 'g'))?.length).toBe(2);
  });

  it('generates an id alias for any placeholder name', () => {
    const template = '<message to="{to}">{body}</message>';
    const result = resolvePlaceholders(template, { to: '${id-route}', body: 'ping' }, { autoGenerate: true });

    const generated = result.generatedIds['route'];
    const id = generated ?? '';
    expect(id).toBeDefined();
    expect(result.generatedIds['to']).toBe(id);
    expect(result.xml).toContain(id);
  });

  it('uses provided values and environment overrides', () => {
    const template = '<message to="{TO_JID}">{body}</message>';
    const result = resolvePlaceholders(template, { body: 'Hello' }, {
      autoGenerate: false,
      env: { TO_JID: 'alice@example.com' },
    });

    expect(result.xml).toContain('alice@example.com');
    expect(result.xml).toContain('Hello');
  });
});

describe('validatePlaceholders', () => {
  it('returns missing user-provided fields', () => {
    const template = '<message to="{to}">{body}</message>';
    const validation = validatePlaceholders(template, { to: 'user@example.com' });

    expect(validation.valid).toBe(false);
    expect(validation.missing).toEqual(['body']);
  });
});
